version: "3"

services:
  webapp:
    container_name: webapp
    restart: always
    build:
      context: ../src/webapp
      dockerfile: Dockerfile
    expose:
      - 5000
    command: gunicorn -w 1 -t 1000 -b 0.0.0.0:4000 wsgi:app
 
